feature/NGM-7637-detect-emoji-picker-open
cobroventures/ng-emoji-picker pull request #15
Opened 2021-06-19 06:49 UTC by adeopura4

* Detect if emoji picker is open
* have a single emoji picker open at any time

2021-06-22 19:58 UTC, bdollinger requested changes

2021-06-22 19:58 UTC, bdollinger commented on js/jquery.emojiarea.js
> +      updateGlobalEmojiPickerVisiblity(this, false);
Why is this call to updateGlobalEmojiPickerVisiblity need to be made if it is made above on line 705?

2021-06-22 20:01 UTC, bdollinger commented on js/jquery.emojiarea.js
> +        window.emojiPickerStatus.visibleEmojiPickerInstance = null;
Would it be better to use updateGlobalEmojiPickerVisiblity to keep the visibility code together?

2021-06-23 03:41 UTC, adeopura4 commented
Hi Brian - I have updated code comments to indicate why I have the code the way I have it. Please review and let me know what you think.

2021-06-23 13:44 UTC, bdollinger approved these changes

2021-06-23 13:44 UTC, merged